name: Auto PR from Dev to Main

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  patch-files:
    runs-on: ubuntu-latest
    env:
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      GH_TOKEN : ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Install uv
        run: wget -qO- https://astral.sh/uv/install.sh | sh
      - name: Clone afixl repo
        run: git clone https://github.com/nocodenolife3742/AFixL.git ./afixl
      - name: Clone this repo
        run: git clone https://github.com/nocodenolife3742/demo-project.git ./demo-project
      - name: prepull docker images
        run: docker pull nocodenolife3742/afixl-env:latest
      - name: Save env variables
        run: |
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> ./afixl/.env
          echo "GH_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> ./afixl/.env
      - name: Run afixl on demo-project
        run: |
          cd afixl
          uv run --env-file .env main.py --path ../demo-project --timeout 1
      - name: PR changes
        run: |
          cd afixl
          uv run --env-file .env scripts/git-patch.py --patches-dir patches --repo-dir ../demo-project/
      # - name: Make changes
      #   run: |
      #     docker --version > generated.txt
      #     git config user.name "github-actions[bot]"
      #     git config user.email "github-actions[bot]@users.noreply.github.com"
      #     git add .
      #     git commit -m "generated"
      #     git push
